# Project Information
site_name: PagerDuty Automation for Incident Remediation Documentation
site_description: A discussion of the uses of automation in IT and its application to Incident Remediation. This guide is to help teams who want to use automation in the service of resolving incidents.
site_author: PagerDuty, Inc.
site_url: https://autoremediation.pagerduty.com/

# Repository
repo_url: https://github.com/PagerDuty/automated-remediation-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme:
  name: pagerduty
  title: 'Automation for Incident Response'

# Contents
nav:
  - Home: 'index.md'
  - Introduction: 'introduction.md'
  - Use Cases for Automation in IT: 'use_cases.md'
  - Automating the Response Process: 'ir_workflows.md'
  - Automation for Incident Resolution: 'automation_ir.md'
  - Getting Started: 'getting_started.md'
  - Regulated Environments: 'regulated_envs.md'
  - Challenges of Automation: 'challenges.md'
  - Additional Resources: 'resources.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.tabbed:

# Development URL, bind to local only.
dev_addr: '127.0.0.1:8000'
