# Project Information
site_name: PagerDuty Automation for Incident Remediation Documentation
site_description: A discussion of the uses of automation in IT and its application to Incident Remediation. This guide is to help teams who want to use automation in the service of resolving incidents.
site_author: PagerDuty, Inc.
site_favicon: 'assets/img/favicon.png'
site_url: https://autoremediation.pagerduty.com

# Repository
repo_url: https://github.com/PagerDuty/automated-remediation-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme: 'material'
theme_dir: 'theme'
extra_css: ['assets/css/pagerduty.css','assets/css/custom.css']
extra_javascript: ['js/github_forks.js']
extra:
  favicon: 'assets/img/favicon.png'
  logo: 'assets/img/icon.png'
  cover: 'assets/img/covers/default.png'
  palette:
    primary: 'green'
    accent: 'blue grey'
  author:
    github: 'PagerDuty'
    twitter: 'PagerDuty'

# Dev URL
dev_addr: '0.0.0.0:8080'

# Contents
pages:
  - Home: 'index.md'
  - Introduction: 'introduction.md'
  - Use Cases for Automation in IT: 'use_cases.md'
  - Automation for Incident Remediation: 'automation_ir.md'
  - Getting Started with Automation for Incident Remediation: 'getting_started.md'
  - Challenges of Automation: 'challenges.md'
  - Conclusion: 'conclusion.md'
  - Resources and Further Reading: 'resources.md'

# Analytics
#google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
